import Head from 'next/head'
import { useEffect, useState } from 'react'
import Button from '../components/Button';
import { Card } from '../components/Card';
import Navbar from '../components/Navbar';
import { getAllPokemon, getPokemon } from "../components/pokemon"
import { loadPokemon } from "../components/Button"

interface pokemonData {
  map(arg0: (pokemon: pokemonData) => Promise<unknown>): any;
  name: string; 
  url: string;
}

const Home = () => {
  const initialURL: string = "https://pokeapi.co/api/v2/pokemon";
  const [loading, setLoading] = useState(true);
  const [pokemonData, setPokemonData] = useState<string[]>([]);
  const [nextPokemon, setNextPokemon] = useState("");
  const [prevPokemon, setPrevPokemon] = useState("");

  useEffect(() => {
    const fetchPokemonData = async() => {
      setLoading(true);
      // 全てのポケモンデータを取得
      let res: unknown = await getAllPokemon(initialURL);
      // 各ポケモンの詳細なデータを取得
      setNextPokemon(res.next);
      setPrevPokemon(res.previous);
      loadPokemon(res.results);
      setLoading(false);
    }
    fetchPokemonData();
  }, [])

  const loadPokemon = async (data: pokemonData) => {
    let _pokemonData = await Promise.all(
      data.map((pokemon: pokemonData) => {
        let pokemonRecord = getPokemon(pokemon.url);
        return pokemonRecord;
      })
    );
    setPokemonData(_pokemonData);
  }

  console.log(nextPokemon);

  return (
    <div>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      {loading ? (
        <h1>ロード中・・・</h1>
      ) : (
        <div className="pokemonCardContainer">
          {pokemonData.map((pokemon, i) => {
            return <Card key={i} pokemon={pokemon} />;
          })}
        </div>
      )}
      <Button 
        setLoading={setLoading} 
        nextPokemon={nextPokemon} 
        loadPokemon={loadPokemon}
        setNextPokemon={setNextPokemon}
        prevPokemon={prevPokemon}
        setPrevPokemon={setPrevPokemon}
      />
    </div>
  )
}

export default Home;