import Head from 'next/head'
import { useEffect, useState } from 'react'
import Button from '../components/Button';
import { Card } from '../components/Card';
import Navbar from '../components/Navbar';
import { getAllPokemon, getPokemon } from "../components/pokemon"

interface pokemonData {
  count: number, 
  next: string, 
  previous: string,
  results: [{
    name: string,
    url: string
  }]
}

interface resData {
  name: string,
  url: string
}

const Home = () => {
  const initialURL: string = "https://pokeapi.co/api/v2/pokemon";
  const [loading, setLoading] = useState(true);
  const [pokemonData, setPokemonData] = useState([]);
  const [nextPokemon, setNextPokemon] = useState("");
  const [prevPokemon, setPrevPokemon] = useState("");

  useEffect(() => {
    const fetchPokemonData = async() => {
      setLoading(true);
      // 全てのポケモンデータを取得
      let res: pokemonData = await getAllPokemon(initialURL);
      // console.log(res);
      // 各ポケモンの詳細なデータを取得
      setNextPokemon(res.next);
      setPrevPokemon(res.previous);
      loadPokemon(res.results);
      setLoading(false);
    }
    fetchPokemonData();
  }, [])

  const loadPokemon = async (data: [resData]) => {
    let _pokemonData = await Promise.all(
      data.map((pokemon) => {
        let pokemonRecord = getPokemon(pokemon.url);
        return pokemonRecord;
      })
    );
    setPokemonData(_pokemonData);
    console.log(_pokemonData);
  }

  // console.log(pokemonData);

  return (
    <div>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      {loading ? (
        <h1>ロード中・・・</h1>
      ) : (
        <div className="pokemonCardContainer">
          {pokemonData.map((pokemon, i) => {
            return <Card key={i} pokemon={pokemon} />;
          })}
        </div>
      )}
      <Button 
        setLoading={setLoading} 
        loadPokemon={loadPokemon}
        nextPokemon={nextPokemon} 
        setNextPokemon={setNextPokemon}
        prevPokemon={prevPokemon}
        setPrevPokemon={setPrevPokemon}
      />
    </div>
  )
}

export default Home;